### ISSUE TITLE
 Issue with Z-axis movement and print dimensions on RF100 after flash of new firmware

### ISSUE THREAD

**Issue by juma-Ju** [probonopd/RF100-Firmware#24]
Hello,

I recently acquired a used RF100 and promptly flashed the latest version of this firmware upon its arrival. However, I've encountered a couple of issues related to the Z-axis movement and print dimensions.

When initiating a print with gcode specifying a 20mm x 20mm x 20mm cube, the printer produces a cube that is 20mm x 20mm wide but only 3mm tall.

Additionally, when manually adjusting the Z-axis through the menu, I've observed that turning the dial all the way up to 110 should move the axis all the way down. However, it only moves approximately a quarter of the way, requiring a printer restart to reset the position to zero before I can move it down to 110 and repeat the process.

I'm uncertain whether this issue stems from the firmware, the main board, or the stepper motor. It would be greatly appreciated if someone could shed light on whether this is a known issue or provide insights into potential causes.

I also have the [gcode file](https://github.com/probonopd/RF100-Firmware/files/13660533/RR_xyzCalibration_cube.zip) if it helps.

Thank you for your assistance.

**Comment by probonopd** [comment]
Sorry, I can't say. This firmware version is very outdated by now, it would probably better to build a new one.

Probably https://github.com/dok-net/RF100 is more usable at this time?
